### PR TITLE
Some fixes

### PR DESCRIPTION
**Pull request by mrextremez**
- Added message of the week to welcome screen interface
- Added face north when clicking compass
- Disabled the blank tab on game frame
- Fixed all of the dialogue issues I could find in rune mysteries
- Fixed a few typos and did a very minor clean up in the dialogue file still a lot more planned soon
- Disabled resizable on the client seeing as it doesnt work correct currently anyways

### CODE REVIEW

**Comment by MitchvanWijngaarden** [comment]
Does the new welcome interface change the 'click here to play now' interface ID from 15812 to any of the following; int[] {17511, 15812, 15801, 15791, 15774, 15767}?

Note that the pre-compiled scripts that are included with the launcher will break if you merge this change.

**Comment by mrextremez** [comment]
That sounds correct, although you can remove the randomization I added and set it as just a single id so it doesn’t break it if you want to @MitchvanWijngaarden

**Comment by MitchvanWijngaarden** [comment]
I don't mind this change. Adjusting a script to support an array of interfaces rather than a single interface is a very small change.
However, script creators should be notified a week or two prior of this upcoming change.

@dginovker then has to re-add the updated or remove the non-compliant scripts to/from the Parabot SDN.

**Comment by dginovker** [comment]
Most scripts just go ahead and start making function calls through Parabot's API, which ignores an open interface anyways. I think the worst scenario here is some scripts do a random click in the middle of the screen then continue on as normal.

@MitchvanWijngaarden

**Pull request merged**
