### PR TITLE
Some more minor clean up

### PR DESCRIPTION
**Pull request by mrextremez**
- Reduced woodcutting code by a lot, cleaned it up and converted the array to an enum
- Moved the login player method to the packet sender
- Deleted some dead code/cleaned up some things
- Moved combat constants from gameconstants.java to combatconstants.java
- Moved dialogue options from clickingbuttons.java to dialogueoptions.java

### CODE REVIEW

**Comment by Gptaqbc** [comment]
Hey you fixed the axe changing when woodcutting?

**Comment by mrextremez** [comment]
@Gptaqbc pretty sure that’s a parabot only bug but I could be wrong.

**Comment by RedSparr0w** [comment]
The axe changes when someone else is woodcutting, it will show the axe the other person is using.

I'm guessing it's a similar problem to how fletching was tied to 1 player at a time.

**Comment by DPSCryptic** [comment]
are you sure?

**Comment by RedSparr0w** [comment]
About 99% certain.

**Comment by DPSCryptic** [comment]
because people were seeing a dragon axe

**Comment by DPSCryptic** [comment]
and i dont think people are doing dks :P

**Pull request merged**
